# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Candidates Finder CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    env:
      COVERAGE_REQUIRED: 70
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Run Lint
      run: |
        set -eu
        # stop the build if there are Python syntax errors or undefined names
        echo the number of files with sintax errors or undefined names are:
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 120 chars wide
        echo the number of files with others errors are:
        flake8 . --count --exit-zero --max-line-length=120 --ignore=E123,E131 --statistics

    - name: Set Coverage Required
      run: |
        echo "Coverage Required: $COVERAGE_REQUIRED"
      env:
        COVERAGE_REQUIRED: ${{ 70 }}
      # run: |
      #   echo "COVERAGE_REQUIRED=70" >> $GITHUB_ENV
      #   echo "Coverage Required: $COVERAGE_REQUIRED"

    - name: Run Coverage Test
      run: |
        echo ${{ env.COVERAGE_REQUIRED }} or echo $COVERAGE_REQUIRED
      # run: |
      #   set -eu
      #   export PYTHONPATH=./
      #   pytest --cov=candidates_finder/ --cov-fail-under=$COVERAGE_REQUIRED -v
      # pytest --cov=candidates_finder/ --cov-fail-under=${{ env.COVERAGE_REQUIRED }} -v
